version: '3'
services:
  events_db:
    container_name: events_db
    image: postgres:14
    environment:
      POSTGRES_DB: events_db
      POSTGRES_USER: events
      POSTGRES_PASSWORD: events
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    container_name: events_keycloak
    image: bitnami/keycloak:23.0.6
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: events_db
      DB_DATABASE: events_db
      DB_USER: events
      DB_PASSWORD: events
      KEYCLOAK_ADMIN: user
      KEYCLOAK_ADMIN_PASSWORD: bitnami
      KC_HHTP_PORT: 8090
    volumes:
      - ./realm.json:/opt/bitnami/keycloak/data/import
    ports:
      - 8090:8080
    depends_on:
      - events_db

  events-api:
    container_name: events_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - events_db
      - keycloak
    ports:
      - "8081:8081"
    environment:
      POSTGRES_URL: jdbc:postgresql://events_db:5432/events_db
      POSTGRES_USER: events
      POSTGRES_PASSWORD: events
volumes:
  pgdata: { }