version: '3'

services:
  events_db:
    container_name: events_db
    image: postgres:14
    environment:
      POSTGRES_DB: events_db
      POSTGRES_USER: events
      POSTGRES_PASSWORD: events
    ports:
      - '4002:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: { }