version: '3'
networks:
  internal-network:

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: labtech_db
      POSTGRES_USER: labtech
      POSTGRES_PASSWORD: labtech
    networks:
      - internal-network
    ports:
      - '4002:5432'

  keycloak:
    image: bitnami/keycloak:23.0.6
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: labtech_db
      DB_USER: labtech
      DB_PASSWORD: labtech
      KEYCLOAK_ADMIN: user
      KEYCLOAK_ADMIN_PASSWORD: bitnami
      KC_HHTP_PORT: 8090
    volumes:
      - ./realm.json:/opt/bitnami/keycloak/data/import
    networks:
      - internal-network
    ports:
      - 8090:8080
    depends_on:
      - postgres
    
  labtech-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8180:8180"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:4002/labtech_db
      POSTGRES_USER: labtech
      POSTGRES_PASSWORD: labtech
    volumes:
      - ./labtech-api:/opt/your-app
    networks:
      - internal-network
    depends_on:
      - postgres
