version: '3'
services:
  events_db:
    container_name: events_db
    image: postgres:14
    environment:
      POSTGRES_DB: events_db
      POSTGRES_USER: events
      POSTGRES_PASSWORD: events
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  events-api:
    container_name: events_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - events_db
      - keycloak
    ports:
      - "8081:8081"
    environment:
      POSTGRES_URL: jdbc:postgresql://events_db:5432/events_db
      POSTGRES_USER: events
      POSTGRES_PASSWORD: events
volumes:
  pgdata: { }