version: "3.8"
services:
  db:
    container_name: labtech_db
    image: postgres:15
    restart: always
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DB: labtech_db
      POSTGRES_PASSWORD: labtech
      POSTGRES_USER: labtech
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./src/main/resources/scripts/initialDb.sql:/docker-entrypoint-initdb.d/001_initialDb.sql
    command: -p 5000

volumes:
  pg_data:
