spring:
  application:
    name: Labtech - Events API
    version: v0.1-Alpha
  security:
    user:
      name: labtech
      password: labtech
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${URL_ISSUER:http://localhost:8090/realms/labtech-events-realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:4002/labtech_db}
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD:labtech}
    username: ${POSTGRES_USER:labtech}
    hikari:
      schema: eventos
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_1
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
server:
  port: 8081
api:
  front: ${API-url:http://localhost:4200}
