version: '3'
networks:
  internal-network:

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: labtech_db
      POSTGRES_USER: labtech
      POSTGRES_PASSWORD: labtech
    networks:
      - internal-network
    ports:
      - '4002:5432'

  keycloak:
    image: bitnami/keycloak:23.0.6
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: labtech_db
      DB_USER: labtech
      DB_PASSWORD: labtech
      KEYCLOAK_ADMIN: user
      KEYCLOAK_ADMIN_PASSWORD: bitnami
    networks:
      - internal-network
    ports:
      - 8090:8080
    depends_on:
      - postgres

