version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5000/labtech_db
      SPRING_DATASOURCE_USERNAME: labtech
      SPRING_DATASOURCE_PASSWORD: labtech
    volumes:
      - ./uploads:/app/uploads

  db:
    container_name: labtech_db
    image: postgres:15
    restart: always
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DB: labtech_db
      POSTGRES_PASSWORD: labtech
      POSTGRES_USER: labtech
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./src/main/resources/scripts/init.sql:/docker-entrypoint-initdb.d/001_init.sql
    command: -p 5000

volumes:
  pg_data:
